import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import Box from '@mui/material/Box';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';


import Sports from '../components/sports';
import Movie from '../components/movie';
import MovieIndi from '../components/movieIndi';

export default function Home() {
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    console.log("valor ", newValue)
    setValue(newValue);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Box sx={{ width: '100%', bgcolor: 'background.paper' }}>
        <Tabs value={value} onChange={handleChange} centered>
          <Tab label="Sports" />
          <Tab label="Movie Accion-Anime" />
          <Tab label="Movie Indi" />
        </Tabs>
      </Box>

      <h1>Sports</h1>
      {value == 0 ?
        <>
          <Sports />
        </> :

        value == 1 ?
          <>
            <Movie />
          </> :
          value == 2 ?
            <>
              <MovieIndi />
            </> :
            <>
            </>}




      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}

        </a>
      </footer>
    </div>
  )
}
